### ISSUE TITLE
sbt-spark-package integration and Spark Packages release

### ISSUE THREAD

**Issue by brkyvz** [tresata/spark-sorted#1]
Hi Tresata Team,

This is a wonderful and very useful Spark Package. Would you consider making an official release for this on the Spark Packages Repository so that Spark users can use this with ease? It would be very easy to make a release if you use the [sbt-spark-package plugin](https://github.com/databricks/sbt-spark-package).
Then users can use this library by simply adding the flag:
`--packages tresata/spark-sorted:0.1` 
to spark-shell, spark-submit or even pyspark. In addition, your package will be ranked higher in the Spark Packages website for having a release!

Users that also use the sbt-spark-package plugin can simply add your dependency as
`spDependencies += "tresata/spark-sorted:0.1`
in their build file.

I can happily submit a pull request for the plugin if you like!

Best,
Burak

**Comment by koertkuipers** [comment]
Merged pulllreq:
https://github.com/tresata/spark-sorted/pull/2
