### ISSUE TITLE
Java api for GroupSorted

### ISSUE THREAD

**Issue by lvsl-deactivated** [tresata/spark-sorted#3]
Hello,

Is it possible to provide a Java API for the library, or some example on how to use it from Java?

**Comment by koertkuipers** [comment]
hey,
i do not think the current api is usable from java.
adding a java api should be possible. i will look into that when i have
some time in next few weeks
best, koert

**Comment by koertkuipers** [comment]
see commit 1d64b687d76e905e2e788b6fba2df10482da77f1

**Comment by lvsl-deactivated** [comment]
awesome, thanks!
